version: '2.1'

services:
  social-media:
    image: social-media
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 19000:19000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js